# Generated by Django 5.0.3 on 2024-03-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
